// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmoPqDiJfHGq_uxnSbfDdWpxiQd9ndts',
    appId: '1:493957623406:android:0f2ef2035f18808003007f',
    messagingSenderId: '493957623406',
    projectId: 'message-app-oceanami-8497a',
    storageBucket: 'message-app-oceanami-8497a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7dwD97HSnLJ7vF9m-hBGgPcyo7Y26VFw',
    appId: '1:493957623406:ios:84246adffc3e64c203007f',
    messagingSenderId: '493957623406',
    projectId: 'message-app-oceanami-8497a',
    storageBucket: 'message-app-oceanami-8497a.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7dwD97HSnLJ7vF9m-hBGgPcyo7Y26VFw',
    appId: '1:493957623406:ios:84246adffc3e64c203007f',
    messagingSenderId: '493957623406',
    projectId: 'message-app-oceanami-8497a',
    storageBucket: 'message-app-oceanami-8497a.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAK2WLSM-0T55Cv8GO3Oy8cWCRP8eDsMg',
    appId: '1:493957623406:web:d6849814f209581303007f',
    messagingSenderId: '493957623406',
    projectId: 'message-app-oceanami-8497a',
    authDomain: 'message-app-oceanami-8497a.firebaseapp.com',
    storageBucket: 'message-app-oceanami-8497a.firebasestorage.app',
    measurementId: 'G-VFNMHH7EWH',
  );

}